In [19]:
import MDAnalysis as mda

import os
import numpy as np
import netCDF4 as netcdf

import time
print(os.getcwd())
prmtop = "/home/jim/BPMFwFFT/examples/amber/3MXW/3MXW_l_b.prmtop"
inpcrd = "/home/jim/BPMFwFFT/examples/amber/3MXW/3MXW_l_b.inpcrd"
ref = mda.Universe(prmtop, inpcrd)
print(ref.coord.positions[0])
out_nc = netcdf.Dataset("trajectory.nc", "w", format="NETCDF4")
print(out_nc.data_model)
three = out_nc.createDimension("three", 3)
natoms = out_nc.createDimension("natoms", ref.atoms.n_atoms)
nconfs = out_nc.createDimension("nconfs", 1)
print(ref.atoms.n_atoms)
positions = out_nc.createVariable("positions", "f8", ("nconfs", "natoms", "three"))
print(out_nc.variables)
refPositions = ref.coord.positions
positions[:,:,:] = refPositions
print("positions =\n{}".format(positions[:,:,:]))
out_nc.close()



/home/jim/BPMFwFFT/notebooks
[-15.759 -15.489  66.157]
NETCDF4
2414
{'positions': <class 'netCDF4._netCDF4.Variable'>
float64 positions(nconfs, natoms, three)
unlimited dimensions: 
current shape = (1, 2414, 3)
filling on, default _FillValue of 9.969209968386869e+36 used}
positions =
[[[-15.75899982 -15.48900032  66.15699768]
  [-16.71467209 -15.75489712  65.96702576]
  [-15.75056267 -14.54753876  66.52262115]
  ...
  [  8.45100021  -0.87800002  61.46300125]
  [  8.45600033  -0.23899999  62.51399994]
  [  9.45411587  -1.51606739  61.15144348]]]


In [20]:
import MDAnalysis as mda

import os
import numpy as np
import netCDF4 as netcdf

et = netcdf.Dataset("example_trajectory.nc", "r")
print(et.data_model)
for dimobj in et.dimensions.values():
    print(dimobj)
print(et.variables)
et.close()


NETCDF4
<class 'netCDF4._netCDF4.Dimension'>: name = 'three', size = 3
<class 'netCDF4._netCDF4.Dimension'>: name = 'natoms', size = 12
<class 'netCDF4._netCDF4.Dimension'>: name = 'nconfs', size = 1000
{'positions': <class 'netCDF4._netCDF4.Variable'>
float64 positions(nconfs, natoms, three)
unlimited dimensions: 
current shape = (1000, 12, 3)
filling on, default _FillValue of 9.969209968386869e+36 used}
